[package]
name = "comms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
rand = "0.8"
rand_distr = "0.4"
itertools = "0.10"

[dev-dependencies]
plotpy = "0.4"
rayon = "1.7"
