[package]
name = "comms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
rand = "0.8"
rand_distr = "0.4"
itertools = "0.10"
rustfft = "6.1"
assert_approx_eq = "1.1"
easyfft = "0.4"
reed-solomon-novelpoly = "1.0"
reed-solomon-erasure = "4.0"

[dev-dependencies]
plotpy = "0.4"
rayon = "1.7"
welch-sde = "0.1"
rstest = "0.18"
csv = "1.3"
pyo3 = {version = "0.20", features = ["auto-initialize"]}
